; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]

;SignTool=st1
AppId={{AA8EAEB4-F26C-4BFB-9863-353E2EFE1232}
AppName=FLaun
AppVersion=1.0.0
AppVerName=FLaun
AppPublisher=ForentDich
DefaultDirName={userappdata}\.flaun
UsePreviousAppDir=yes
DisableDirPage=no
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
AppendDefaultDirName=yes
OutputBaseFilename=FLaun_Setup
SetupIconFile=C:\Code\FLaun\FLaun\Resources\Icons\FLaunSetupIcon.ico
Compression=zip
WizardStyle=modern
WizardSmallImageFile=C:\Users\forent\Pictures\Photoshop\FSetup.bmp
WizardImageFile=C:\Users\forent\Pictures\Photoshop\FSBanner.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked


[Files]
Source: "C:\Code\FLaun\ToPublish\FLaun.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Code\FLaun\ToPublish\Resources\*"; DestDir: "{app}\Resources"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\.myp\OpenWithProgids"; ValueType: string; ValueName: "FLaunSetup.myp"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\FLaunSetup.myp"; ValueType: string; ValueName: ""; ValueData: "FLaun Setup"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\FLaunSetup.myp\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\FLaun.exe,0"
Root: HKA; Subkey: "Software\Classes\FLaunSetup.myp\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\FLaun.exe"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\FLaun.exe\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\FLaun"; Filename: "{app}\FLaun.exe"
Name: "{autodesktop}\FLaun"; Filename: "{app}\FLaun.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\FLaun.exe"; Description: "{cm:LaunchProgram,FLaun}"; Flags: nowait postinstall skipifsilent

